### PR TITLE
B dev

### LINKED ISSUE #19: Implement talent authentication
Implement signin and signup auth using jwt and bcrypt
- [x] signin
- [x] signup

### PR DESCRIPTION
**Pull request by betiniakarandut**
Implemented Talent Authentication

### CODE REVIEW

**Review by Ayobami6 — CHANGES_REQUESTED** [review]
Good bro, 
Please can you reopen the pull request to staging instead of main, for now all dev changes are staged in the staging branch.
Thank you

**Review by Ayobami6 — APPROVED** [review]
This test is great, lets use this instead of the later one with the jest.mock.
Also lets call it route what do you think?
Checkout the dbTestConnection.ts its contains the db test connection utils function

**Review by Ayobami6 — APPROVED** [review]
Awesome bro!

**Review by Ayobami6 — COMMENTED** [review]
This brilliant bro, But why don't we stick with the previous test you wrote, the one with the signup and signin endpoint. I mean point of writing the test is to help us detect any bugs easily before we actually detect them ourselves and those previous test is gracefully helping us do that which is simple and precise. for example if test fail for /signup we can easily traceback to signup controller and debug why our test was failing which could be cause by various number of things like the controller is not sending the data to the database, or  could not fetch data or there was a typo in the controller endpoint and so on...
I hope you get the point, more like an integration test.

**Comment by betiniakarandut** [comment]
> This test is great, lets use this instead of the later one with the jest.mock. Also lets call it route what do you think? Checkout the dbTestConnection.ts its contains the db test connection utils function

Okay on it.

**Pull request closed without merging**
